<? $this->render_partial('site:widget:social', array('list' => array(
  array('coding', 'GitHub', 'http://github.com/ericmuyser/'),
  array('coding', 'Google Code', 'http://code.google.com/u/Eric.Muyser/'),
  array('coding', 'Stack Overflow', 'http://stackoverflow.com/users/119301/eric-muyser/'),
  array('coding', 'Super User', 'http://superuser.com/users/20454/eric-muyser/'),
  array('coding', 'Server Fault', 'http://serverfault.com/users/11696/eric-muyser'),
  array('coding', 'Snipplr', 'http://snipplr.com/users/ericmuyser'),
  array('coding', 'Refactor MC', 'http://refactormycode.com/users/2396'),
  array('coding', 'Launchpad', 'https://launchpad.net/~ericmuyser'),
  array('coding', 'CBoard', 'http://cboard.cprogramming.com/member.php?u=12405'),
  array('coding', 'GameDev', 'http://www.gamedev.net/community/forums/viewprofile.asp?mode=cp&ID=146656'),
  array('personal', 'Facebook', 'http://www.facebook.com/ericmuyser'),
  array('personal', 'Twitter', 'http://twitter.com/ericmuyser/'),
  array('personal', 'YouTube', 'http://www.youtube.com/user/EricMuyser'),
  array('personal', 'Netvibes', 'http://www.netvibes.com/ericmuyser'),
  array('personal', 'Digg', 'http://digg.com/users/ericmuyser'),
  array('personal', 'eBay', 'http://myworld.ebay.ca/eric.muyser'),
  array('personal', 'Blippr', 'http://www.blippr.com/profiles/ericmuyser'),
  array('personal', 'Flickr', 'http://www.flickr.com/people/ericmuyser/'),
  array('personal', 'LinkedIn', 'http://ca.linkedin.com/in/ericmuyser/'),
  array('personal', 'Stumble Upon', 'http://www.stumbleupon.com/stumbler/ericmuyser/'),
  array('personal', 'IMDB', 'http://www.imdb.com/user/ur10107022/boards/profile'),
  array('personal', 'Vimeo', 'http://www.vimeo.com/user2849981/'),
  array('personal', 'Last FM', 'http://www.last.fm/user/ericmuyser/'),
  array('personal', 'Bitly', 'http://bit.ly/user/recent/ericmuyser'),
  array('personal', 'Delicious', 'http://delicious.com/ericmuyser'),
  array('gaming', 'Steam', 'http://steamcommunity.com/id/daemn/'),
  array('gaming', 'Xfire', 'http://www.xfire.com/profile/daemn/'),
  array('gaming', 'Raptr', 'http://raptr.com/daemn'),
  array('gaming', 'Windows Live', 'http://live.xbox.com/en-US/profile/profile.aspx?GamerTag=EricMuyser'),
  array('work', 'vWorker', 'http://www.vworker.com/RentACoder/DotNet/SoftwareCoders/ShowBioInfo.aspx?lngAuthorId=6750277&intTabSelectedId=2'),
  array('work', 'Freelancer', 'http://www.freelancer.com/users/531446.html')
))) ?>
